ALTER TABLE media_files ADD COLUMN IF NOT EXISTS video_id VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS thumbnail_url TEXT NOT NULL DEFAULT '';
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS embeded_html TEXT NOT NULL DEFAULT '';
