-- Convert audit columns (created_at, updated_at, deleted_at) from TIMESTAMPTZ to BIGINT Unix seconds.

ALTER TABLE permissions
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE permissions
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE roles
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE roles
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE users
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT,
  ALTER COLUMN deleted_at TYPE BIGINT USING EXTRACT(EPOCH FROM deleted_at)::BIGINT;

ALTER TABLE users
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE course_levels
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE course_levels
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE course_topics
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE course_topics
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE course_outcomes
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE course_outcomes
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE course_skills
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE course_skills
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE tags
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE tags
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE media_files
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT,
  ALTER COLUMN deleted_at TYPE BIGINT USING EXTRACT(EPOCH FROM deleted_at)::BIGINT;

ALTER TABLE media_files
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE media_pending_cloud_cleanup
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT,
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE media_pending_cloud_cleanup
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE system_app_config
  ALTER COLUMN updated_at TYPE BIGINT USING EXTRACT(EPOCH FROM updated_at)::BIGINT;

ALTER TABLE system_app_config
  ALTER COLUMN updated_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);

ALTER TABLE system_privileged_users
  ALTER COLUMN created_at TYPE BIGINT USING EXTRACT(EPOCH FROM created_at)::BIGINT;

ALTER TABLE system_privileged_users
  ALTER COLUMN created_at SET DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT);
