package application

// rolesPermissionT declares which permission_id each role gets. Tags drive cmd/syncrolepermissions
// (role name + perm_id); field values are unused.
var RolePermissions = struct {
	// sysadmin — full catalog P1–P40
	Sysadmin_ProfileRead                     string `role:"sysadmin" perm_id:"P1"`
	Sysadmin_ProfileUpdate                   string `role:"sysadmin" perm_id:"P2"`
	Sysadmin_ProfileDelete                   string `role:"sysadmin" perm_id:"P3"`
	Sysadmin_ProfileCreate                   string `role:"sysadmin" perm_id:"P4"`
	Sysadmin_CourseRead                      string `role:"sysadmin" perm_id:"P5"`
	Sysadmin_CourseUpdate                    string `role:"sysadmin" perm_id:"P6"`
	Sysadmin_CourseDelete                    string `role:"sysadmin" perm_id:"P7"`
	Sysadmin_CourseCreate                    string `role:"sysadmin" perm_id:"P8"`
	Sysadmin_CourseInstructorRead            string `role:"sysadmin" perm_id:"P9"`
	Sysadmin_UserRead                        string `role:"sysadmin" perm_id:"P10"`
	Sysadmin_UserUpdate                      string `role:"sysadmin" perm_id:"P11"`
	Sysadmin_UserDelete                      string `role:"sysadmin" perm_id:"P12"`
	Sysadmin_UserCreate                      string `role:"sysadmin" perm_id:"P13"`
	Sysadmin_CourseLevelRead                 string `role:"sysadmin" perm_id:"P14"`
	Sysadmin_CourseLevelCreate               string `role:"sysadmin" perm_id:"P15"`
	Sysadmin_CourseLevelUpdate               string `role:"sysadmin" perm_id:"P16"`
	Sysadmin_CourseLevelDelete               string `role:"sysadmin" perm_id:"P17"`
	Sysadmin_TopicRead                       string `role:"sysadmin" perm_id:"P18"`
	Sysadmin_TopicCreate                     string `role:"sysadmin" perm_id:"P19"`
	Sysadmin_TopicUpdate                     string `role:"sysadmin" perm_id:"P20"`
	Sysadmin_TopicDelete                     string `role:"sysadmin" perm_id:"P21"`
	Sysadmin_CourseOutcomeRead               string `role:"sysadmin" perm_id:"P30"`
	Sysadmin_CourseOutcomeCreate             string `role:"sysadmin" perm_id:"P31"`
	Sysadmin_CourseOutcomeUpdate             string `role:"sysadmin" perm_id:"P32"`
	Sysadmin_CourseOutcomeDelete             string `role:"sysadmin" perm_id:"P33"`
	Sysadmin_CourseSkillRead                 string `role:"sysadmin" perm_id:"P34"`
	Sysadmin_CourseSkillCreate               string `role:"sysadmin" perm_id:"P35"`
	Sysadmin_CourseSkillUpdate               string `role:"sysadmin" perm_id:"P36"`
	Sysadmin_CourseSkillDelete               string `role:"sysadmin" perm_id:"P37"`
	Sysadmin_TagRead                         string `role:"sysadmin" perm_id:"P22"`
	Sysadmin_TagCreate                       string `role:"sysadmin" perm_id:"P23"`
	Sysadmin_TagUpdate                       string `role:"sysadmin" perm_id:"P24"`
	Sysadmin_TagDelete                       string `role:"sysadmin" perm_id:"P25"`
	Sysadmin_MediaFileRead                   string `role:"sysadmin" perm_id:"P26"`
	Sysadmin_MediaFileCreate                 string `role:"sysadmin" perm_id:"P27"`
	Sysadmin_MediaFileUpdate                 string `role:"sysadmin" perm_id:"P28"`
	Sysadmin_MediaFileDelete                 string `role:"sysadmin" perm_id:"P29"`
	Sysadmin_SysadminModify                  string `role:"sysadmin" perm_id:"P38"`
	Sysadmin_AdminModify                     string `role:"sysadmin" perm_id:"P39"`
	Sysadmin_InstructorModify                string `role:"sysadmin" perm_id:"P40"`
	Sysadmin_InstructorRosterRead            string `role:"sysadmin" perm_id:"P41"`
	Sysadmin_InstructorRosterCreate          string `role:"sysadmin" perm_id:"P42"`
	Sysadmin_InstructorRosterDelete          string `role:"sysadmin" perm_id:"P43"`
	Sysadmin_InstructorApplicationRead       string `role:"sysadmin" perm_id:"P44"`
	Sysadmin_InstructorApplicationCreate     string `role:"sysadmin" perm_id:"P45"`
	Sysadmin_InstructorApplicationUpdate     string `role:"sysadmin" perm_id:"P46"`
	Sysadmin_InstructorApplicationDelete     string `role:"sysadmin" perm_id:"P47"`
	Sysadmin_InstructorApplicationApprove    string `role:"sysadmin" perm_id:"P48"`
	Sysadmin_InstructorApplicationReject     string `role:"sysadmin" perm_id:"P49"`
	Sysadmin_InstructorProfileRead           string `role:"sysadmin" perm_id:"P50"`
	Sysadmin_InstructorProfileCreate         string `role:"sysadmin" perm_id:"P51"`
	Sysadmin_InstructorProfileUpdate         string `role:"sysadmin" perm_id:"P52"`
	Sysadmin_InstructorProfileDelete         string `role:"sysadmin" perm_id:"P53"`
	Sysadmin_InstructorExpertiseRead         string `role:"sysadmin" perm_id:"P54"`
	Sysadmin_InstructorExpertiseCreate       string `role:"sysadmin" perm_id:"P55"`
	Sysadmin_InstructorExpertiseUpdate       string `role:"sysadmin" perm_id:"P56"`
	Sysadmin_InstructorExpertiseDelete       string `role:"sysadmin" perm_id:"P57"`
	Sysadmin_InstructorTicketClose           string `role:"sysadmin" perm_id:"P58"`
	Sysadmin_CourseReviewRead                string `role:"sysadmin" perm_id:"P59"`
	Sysadmin_CourseReviewApprove             string `role:"sysadmin" perm_id:"P60"`
	Sysadmin_CourseReviewReject              string `role:"sysadmin" perm_id:"P61"`
	Sysadmin_CourseCatalogRead               string `role:"sysadmin" perm_id:"P62"`
	Sysadmin_CourseCatalogTrash              string `role:"sysadmin" perm_id:"P63"`
	Sysadmin_CourseTrashRead                 string `role:"sysadmin" perm_id:"P64"`
	Sysadmin_CourseTrashRestore              string `role:"sysadmin" perm_id:"P65"`
	Sysadmin_CourseTrashDelete               string `role:"sysadmin" perm_id:"P66"`
	Sysadmin_CourseCollaboratorCandidateRead string `role:"sysadmin" perm_id:"P67"`
	// admin — profile + course + user (no course_instructor)
	Admin_ProfileRead                     string `role:"admin" perm_id:"P1"`
	Admin_ProfileUpdate                   string `role:"admin" perm_id:"P2"`
	Admin_ProfileDelete                   string `role:"admin" perm_id:"P3"`
	Admin_ProfileCreate                   string `role:"admin" perm_id:"P4"`
	Admin_CourseRead                      string `role:"admin" perm_id:"P5"`
	Admin_CourseUpdate                    string `role:"admin" perm_id:"P6"`
	Admin_CourseDelete                    string `role:"admin" perm_id:"P7"`
	Admin_CourseCreate                    string `role:"admin" perm_id:"P8"`
	Admin_UserRead                        string `role:"admin" perm_id:"P10"`
	Admin_UserUpdate                      string `role:"admin" perm_id:"P11"`
	Admin_UserDelete                      string `role:"admin" perm_id:"P12"`
	Admin_UserCreate                      string `role:"admin" perm_id:"P13"`
	Admin_CourseLevelRead                 string `role:"admin" perm_id:"P14"`
	Admin_CourseLevelCreate               string `role:"admin" perm_id:"P15"`
	Admin_CourseLevelUpdate               string `role:"admin" perm_id:"P16"`
	Admin_CourseLevelDelete               string `role:"admin" perm_id:"P17"`
	Admin_TopicRead                       string `role:"admin" perm_id:"P18"`
	Admin_TopicCreate                     string `role:"admin" perm_id:"P19"`
	Admin_TopicUpdate                     string `role:"admin" perm_id:"P20"`
	Admin_TopicDelete                     string `role:"admin" perm_id:"P21"`
	Admin_CourseOutcomeRead               string `role:"admin" perm_id:"P30"`
	Admin_CourseOutcomeCreate             string `role:"admin" perm_id:"P31"`
	Admin_CourseOutcomeUpdate             string `role:"admin" perm_id:"P32"`
	Admin_CourseOutcomeDelete             string `role:"admin" perm_id:"P33"`
	Admin_CourseSkillRead                 string `role:"admin" perm_id:"P34"`
	Admin_CourseSkillCreate               string `role:"admin" perm_id:"P35"`
	Admin_CourseSkillUpdate               string `role:"admin" perm_id:"P36"`
	Admin_CourseSkillDelete               string `role:"admin" perm_id:"P37"`
	Admin_TagRead                         string `role:"admin" perm_id:"P22"`
	Admin_TagCreate                       string `role:"admin" perm_id:"P23"`
	Admin_TagUpdate                       string `role:"admin" perm_id:"P24"`
	Admin_TagDelete                       string `role:"admin" perm_id:"P25"`
	Admin_MediaFileRead                   string `role:"admin" perm_id:"P26"`
	Admin_MediaFileCreate                 string `role:"admin" perm_id:"P27"`
	Admin_MediaFileUpdate                 string `role:"admin" perm_id:"P28"`
	Admin_MediaFileDelete                 string `role:"admin" perm_id:"P29"`
	Admin_AdminModify                     string `role:"admin" perm_id:"P39"`
	Admin_InstructorModify                string `role:"admin" perm_id:"P40"`
	Admin_InstructorRosterRead            string `role:"admin" perm_id:"P41"`
	Admin_InstructorRosterCreate          string `role:"admin" perm_id:"P42"`
	Admin_InstructorRosterDelete          string `role:"admin" perm_id:"P43"`
	Admin_InstructorApplicationRead       string `role:"admin" perm_id:"P44"`
	Admin_InstructorApplicationCreate     string `role:"admin" perm_id:"P45"`
	Admin_InstructorApplicationUpdate     string `role:"admin" perm_id:"P46"`
	Admin_InstructorApplicationDelete     string `role:"admin" perm_id:"P47"`
	Admin_InstructorApplicationApprove    string `role:"admin" perm_id:"P48"`
	Admin_InstructorApplicationReject     string `role:"admin" perm_id:"P49"`
	Admin_InstructorProfileRead           string `role:"admin" perm_id:"P50"`
	Admin_InstructorProfileCreate         string `role:"admin" perm_id:"P51"`
	Admin_InstructorProfileUpdate         string `role:"admin" perm_id:"P52"`
	Admin_InstructorProfileDelete         string `role:"admin" perm_id:"P53"`
	Admin_InstructorExpertiseRead         string `role:"admin" perm_id:"P54"`
	Admin_InstructorExpertiseCreate       string `role:"admin" perm_id:"P55"`
	Admin_InstructorExpertiseUpdate       string `role:"admin" perm_id:"P56"`
	Admin_InstructorExpertiseDelete       string `role:"admin" perm_id:"P57"`
	Admin_InstructorTicketClose           string `role:"admin" perm_id:"P58"`
	Admin_CourseReviewRead                string `role:"admin" perm_id:"P59"`
	Admin_CourseReviewApprove             string `role:"admin" perm_id:"P60"`
	Admin_CourseReviewReject              string `role:"admin" perm_id:"P61"`
	Admin_CourseCatalogRead               string `role:"admin" perm_id:"P62"`
	Admin_CourseCatalogTrash              string `role:"admin" perm_id:"P63"`
	Admin_CourseTrashRead                 string `role:"admin" perm_id:"P64"`
	Admin_CourseTrashRestore              string `role:"admin" perm_id:"P65"`
	Admin_CourseTrashDelete               string `role:"admin" perm_id:"P66"`
	Admin_CourseCollaboratorCandidateRead string `role:"admin" perm_id:"P67"`
	// instructor
	Instructor_ProfileRead                     string `role:"instructor" perm_id:"P1"`
	Instructor_CourseRead                      string `role:"instructor" perm_id:"P5"`
	Instructor_CourseUpdate                    string `role:"instructor" perm_id:"P6"`
	Instructor_CourseDelete                    string `role:"instructor" perm_id:"P7"`
	Instructor_CourseInstructorRead            string `role:"instructor" perm_id:"P9"`
	Instructor_UserRead                        string `role:"instructor" perm_id:"P10"`
	Instructor_CourseLevelRead                 string `role:"instructor" perm_id:"P14"`
	Instructor_TopicRead                       string `role:"instructor" perm_id:"P18"`
	Instructor_CourseOutcomeRead               string `role:"instructor" perm_id:"P30"`
	Instructor_CourseSkillRead                 string `role:"instructor" perm_id:"P34"`
	Instructor_TagRead                         string `role:"instructor" perm_id:"P22"`
	Instructor_MediaFileRead                   string `role:"instructor" perm_id:"P26"`
	Instructor_MediaFileCreate                 string `role:"instructor" perm_id:"P27"`
	Instructor_MediaFileUpdate                 string `role:"instructor" perm_id:"P28"`
	Instructor_MediaFileDelete                 string `role:"instructor" perm_id:"P29"`
	Instructor_InstructorModify                string `role:"instructor" perm_id:"P40"`
	Instructor_InstructorApplicationCreate     string `role:"instructor" perm_id:"P45"`
	Instructor_InstructorApplicationDelete     string `role:"instructor" perm_id:"P47"`
	Instructor_InstructorApplicationReject     string `role:"instructor" perm_id:"P49"`
	Instructor_InstructorExpertiseCreate       string `role:"instructor" perm_id:"P55"`
	Instructor_InstructorExpertiseUpdate       string `role:"instructor" perm_id:"P56"`
	Instructor_InstructorExpertiseDelete       string `role:"instructor" perm_id:"P57"`
	Instructor_InstructorTicketClose           string `role:"instructor" perm_id:"P58"`
	Instructor_CourseCollaboratorCandidateRead      string `role:"instructor" perm_id:"P67"`
	Instructor_InstructorApplicationSubmitBlocked   string `role:"instructor" perm_id:"P68"`
	// learner
	Learner_ProfileRead                 string `role:"learner" perm_id:"P1"`
	Learner_CourseRead                  string `role:"learner" perm_id:"P5"`
	Learner_UserRead                    string `role:"learner" perm_id:"P10"`
	Learner_CourseLevelRead             string `role:"learner" perm_id:"P14"`
	Learner_TopicRead                   string `role:"learner" perm_id:"P18"`
	Learner_CourseOutcomeRead           string `role:"learner" perm_id:"P30"`
	Learner_CourseSkillRead             string `role:"learner" perm_id:"P34"`
	Learner_TagRead                     string `role:"learner" perm_id:"P22"`
	Learner_MediaFileRead               string `role:"learner" perm_id:"P26"`
	Learner_InstructorApplicationCreate string `role:"learner" perm_id:"P45"`
}{}
